New-ADGroup -Name "MarketingovyTym" -GroupScope Global -Path "OU=Marketing,DC=domaci,DC=server"
New-ADGroup -Name "HRTym" -GroupScope Global -Path "OU=HR,DC=domaci,DC=server"
New-ADGroup -Name "ITAdmini" -GroupScope Global -Path "OU=IT,DC=domaci,DC=server"
New-ADGroup -Name "UcetniTym" -GroupScope Global -Path "OU=Ucetnictvi,DC=domaci,DC=server"
Add-ADGroupMember -Identity "MarketingovyTym" -Members "pavladvorakova"
Add-ADGroupMember -Identity "HRTym" -Members "romanacerna"
Add-ADGroupMember -Identity "UcetniTym" -Members "dominikanova"
Add-ADGroupMember -Identity "ITAdmini" -Members "patriknovak"
Add-ADGroupMember -Identity "MarketingovyTym" -Members "petrrovny"